version: '3.8'
services:
  proxy_core:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: sh -c "python -m proxy"

  nginx:
    image: nginx
